# Generated by Django 2.2.24 on 2021-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bitcoins',
            field=models.FloatField(default=9.542605591072748),
        ),
    ]
